### ISSUE TITLE
TypeError: QgsProcessingAlgorithm.parameterAsSink(): argument 5 has unexpected type 'int'

### ISSUE THREAD

**Issue by imgc86** [kowalski93/Green-View-Index-for-QGIS#3]
I am trying to use Green View Index plugin tools and I get the following error
2024-05-14T09:03:24     CRITICAL    Traceback (most recent call last):
              File "C:\Users/imgonzalez3/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\green_view_index\greenviewindex\calculate_green_view_index_algorithm.py", line 225, in processAlgorithm
              (sink, dest_id) = self.parameterAsSink(
             TypeError: QgsProcessingAlgorithm.parameterAsSink(): argument 5 has unexpected type 'int'

Could someone provide a solution?
Thanks

**Comment by kowalski93** [comment]
Please use a stable (LTR) version of QGIS and not the most recent one.

**Comment by imgc86** [comment]
I have the latest LTR:

Versión de QGIS: 3.34.4-Prizren
Revisión del código de QGIS: decd43dc
Versión de Qt: 5.15.3
Python version: 3.9.18
Versión de GDAL: 3.8.4
Versión de GEOS: 3.12.1-CAPI-1.18.1
Versión de PROJ: Rel. 9.3.1, December 1st, 2023
PDAL version: 2.6.0 (git-version: 3fced5)

**Comment by kowalski93** [comment]
Located the issue, I will update the plugin next week.

**Comment by joytvxq** [comment]
Hi I have the same problem. I just wonder is there any chance the plugin will be updated before next Tuesday? 

Thank you!!

**Comment by kowalski93** [comment]
The plugin has been updated in the githup repo, you can download it and install as zip. It will be updated on the QGIS repository as well soon, although that's not entirely up to me, sometimes it takes days before the new upload is updated.
